Fix Rust lints failing on `main` (#249)
Since this is blocking other PRs:

```
    Checking integration-test v0.0.0 (/home/runner/work/heroku-java-metrics-agent/heroku-java-metrics-agent/integration-test)
error: usage of `.map(...).all(identity)`
  --> src/main.rs:88:10
   |
88 |           .map(|window| {
   |  __________^
89 | |             match window {
90 | |                 [earlier_request, later_request] => later_request
91 | |                     .time
...  |
98 | |         })
99 | |         .all(identity));
   | |______________________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_all_any_identity
   = note: `-D clippy::map-all-any-identity` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::map_all_any_identity)]`
help: use `.all(...)` instead
   |
88 ~         .all(|window| {
89 +             match window {
90 +                 [earlier_request, later_request] => later_request
91 +                     .time
92 +                     .duration_since(earlier_request.time)
93 +                     .is_ok_and(|duration| {
94 +                         duration.as_millis() > 4500 && duration.as_millis() < 5500
95 +                     }),
96 +                 _ => false,
97 +             }
98 ~         }));
   |
```